version: "3.7"

services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend-spring
    environment:
      API_HOST: ${API_HOST}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - network
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ghostkitchen
    networks:
      - network

networks:
  network:
